"""Public analysis API through Phase 6: structure, liquidity, displacement, and FVGs."""

from smcsignal.analysis.config import AnalysisConfig, load_analysis_config
from smcsignal.analysis.displacement import (
    ATRReference,
    DisplacementAnalyzer,
    DisplacementConfig,
    DisplacementEvent,
    DisplacementMetrics,
    DisplacementSnapshot,
    SweepContext,
    analyze_displacement,
    load_displacement_config,
)
from smcsignal.analysis.errors import AnalysisConfigurationError, AnalysisError, AnalysisInputError
from smcsignal.analysis.fvg import (
    FVGAnalyzer,
    FVGConfig,
    FVGEvent,
    FVGSnapshot,
    analyze_fvg,
    load_fvg_config,
)
from smcsignal.analysis.liquidity import (
    InvalidationReason,
    LiquidityAnalyzer,
    LiquidityConfig,
    LiquidityKind,
    LiquidityPool,
    LiquiditySide,
    LiquiditySnapshot,
    ObservedCandle,
    PoolStatus,
    StructureContext,
    SweepEvent,
    SwingEvidence,
    analyze_liquidity,
    candle_close_time,
    evidence_json,
    load_liquidity_config,
)
from smcsignal.analysis.models import (
    AnalysisSnapshot,
    StructureEvent,
    StructureEventKind,
    Swing,
    SwingKind,
    TrendDirection,
    TrendState,
)
from smcsignal.analysis.provenance import (
    CandleReference,
    EvidenceProvenance,
    EvidenceReference,
    ProvenancedEvidence,
    SeriesProvenance,
)
from smcsignal.analysis.structure import MarketStructureAnalyzer, analyze
from smcsignal.analysis.swings import SwingDetector, detect_swings
from smcsignal.analysis.trend import classify_trend

__all__ = [
    "FVGAnalyzer",
    "FVGConfig",
    "FVGEvent",
    "FVGSnapshot",
    "analyze_fvg",
    "load_fvg_config",
    "ATRReference",
    "DisplacementAnalyzer",
    "DisplacementConfig",
    "DisplacementEvent",
    "DisplacementMetrics",
    "DisplacementSnapshot",
    "SweepContext",
    "analyze_displacement",
    "load_displacement_config",
    "InvalidationReason",
    "LiquidityAnalyzer",
    "LiquidityConfig",
    "LiquidityKind",
    "LiquidityPool",
    "LiquiditySide",
    "LiquiditySnapshot",
    "ObservedCandle",
    "PoolStatus",
    "StructureContext",
    "SweepEvent",
    "SwingEvidence",
    "analyze_liquidity",
    "candle_close_time",
    "evidence_json",
    "load_liquidity_config",
    "AnalysisConfig",
    "AnalysisConfigurationError",
    "AnalysisError",
    "AnalysisInputError",
    "AnalysisSnapshot",
    "CandleReference",
    "EvidenceProvenance",
    "EvidenceReference",
    "ProvenancedEvidence",
    "SeriesProvenance",
    "MarketStructureAnalyzer",
    "StructureEvent",
    "StructureEventKind",
    "Swing",
    "SwingDetector",
    "SwingKind",
    "TrendDirection",
    "TrendState",
    "analyze",
    "classify_trend",
    "detect_swings",
    "load_analysis_config",
]
